import os

def build_project(project_name):
    """
    MVP build stub.
    Creates a placeholder APK inside backend/outputs/<project_name>/
    """

    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(base_dir, "outputs", project_name)

    os.makedirs(output_dir, exist_ok=True)

    apk_path = os.path.join(output_dir, "app-debug.apk")

    # Placeholder APK file
    with open(apk_path, "w") as f:
        f.write("APK PLACEHOLDER — GENERATED BY APPFORGE AI")

    return apk_path
