import os

def build_project(project_path):
    """
    MVP build stub.
    Later this will run Gradle + emulator.
    """

    output_dir = project_path
    os.makedirs(output_dir, exist_ok=True)

    apk_path = os.path.join(output_dir, "app-debug.apk")

    # Placeholder APK file
    with open(apk_path, "w") as f:
        f.write("APK PLACEHOLDER — GENERATED BY APPFORGE AI")

    return apk_path
